service: scraping-auction-getter-actions
provider:
  name: aws
  runtime: python3.8
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_auction:
    handler: handler.get
    events:
      - http:
          path: auction
          method: get

plugins:
  - serverless-python-requirements
  
